import type { Metadata } from "next";
import { CartProvider } from "@/context/CartContext";
import CartMenu from "@/components/CartMenu";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <CartProvider>
          <main className="min-h-screen max-w-5xl mx-auto px-4 py-6">
            <CartMenu />
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
